language: haskell

env:
  # - GHCVER=6.12.3
  # - GHCVER=7.0.1
  # - GHCVER=7.0.2
  # - GHCVER=7.0.3
  # - GHCVER=7.0.4
  # - GHCVER=7.2.1
  # - GHCVER=7.2.2
  # - GHCVER=7.4.1
  # - GHCVER=7.4.2
  - GHCVER=7.6.1
  - GHCVER=7.6.2
  - GHCVER=7.6.3
  - GHCVER=7.8.1
  - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=6.12.3
    - env: GHCVER=7.0.1
    - env: GHCVER=7.0.2
    - env: GHCVER=7.0.3
    - env: GHCVER=7.0.4
    - env: GHCVER=7.2.1
    - env: GHCVER=7.2.2
    - env: GHCVER=7.4.1
    - env: GHCVER=7.4.2
    - env: GHCVER=7.6.1
    - env: GHCVER=7.8.1
    - env: GHCVER=head

before_install:
  - git submodule update --init --recursive
  # Install the GHC we want from hvr's PPA
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install alex happy cpphs cabal-install-1.18 ghc-$GHCVER
  - export CABAL=cabal-1.18
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - $CABAL update
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update

install:
  - $CABAL install --dependencies-only --enable-tests
  - $CABAL configure --enable-tests -v2

script:
  - $CABAL build
  - $CABAL test --show-details=always
